### PR TITLE
Adding python examples to list/add/update/delete various PSM objects

### PR DESCRIPTION
**Pull request by guptaankit23**
Adding python examples to list/add/update/delete various PSM objects. This is phase1 and we will keep adding more use cases.

### CODE REVIEW

**Review by jsilberm — CHANGES_REQUESTED** [review]
1.  Looks like your IDE is truncating the newline at the end of each file.   Can you please fix that?
2. Could you please add a `requirements.txt` file in the `examples` directory and add `click` (maybe others too) into the file?

**Comment by guptaankit23** [comment]
> * Looks like your IDE is truncating the newline at the end of each file.   Can you please fix that?
> * Could you please add a `requirements.txt` file in the `examples` directory and add `click` (maybe others too) into the file?

Updated the files & requirements.txt is added as well.

**Review by jsilberm — CHANGES_REQUESTED** [review]
Almost.  `client/python/examples/dss_network_list.py` is still showing no newline.

**Review by jsilberm — APPROVED** [review]

**Comment by jsilberm** [comment]
LGTM.  Thanks.

**Pull request merged**
