### PR TITLE
update to requirements.txt

### PR DESCRIPTION
**Pull request by lindalwang**
added tzlocal and tabulate for issue #6

### CODE REVIEW

**Comment by jainvipin** [comment]
@RishabhPatil - can you please LGTM it?

**Comment by RishabhPatil** [comment]
@lindalwang We dont need tzlocal anymore right?
Other than that LGTM!

**Comment by lindalwang** [comment]
@RishabhPatil Thanks for the reminder! I removed the tzlocal line.

**Review by RishabhPatil — APPROVED** [review]
LGTM

**Pull request merged**
